"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

# import os
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent # manage.py-in oldugu yer base directorydir


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0qpjm#l1p+u$kvdbkh_4i73+58812gwpgb06djdy+7@6k!9%db' #sonradan .venv ichine salinacaq,gizli qalmalidir

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True # urlde xeta olarsa gosterilen errorun gizlinde olmasi or aciq olmasi

DEBUG = os.environ.get("DEBUG", False) != "False"  #bu kodun qarşılığı production-da işləyəndə False olacaq..
#.. local-da işləyəndə True olacaq. Səbəbi, localda xətaları rahat görə bilməyimiz üçün
PROD = not DEBUG

# ALLOWED_HOST  S = [] #men proyketimi yaynladighim IP adresimi bura qeyd edirem
#icaze verilen host-lardir
# yanlış link girilərsə o zaman açıq error vermir/ * isə bütün errorları əhatə edir

# DEBUG = True
ALLOWED_HOSTS = ["*"]


# Application definition
# Jangonun verdiyi pluslar
INSTALLED_APPS = [
    'django.contrib.admin', #
    'django.contrib.auth', # authontication, login or logout olmasi
    'django.contrib.contenttypes',
    'django.contrib.sessions', # her defe tekrar login olmamaq uchun istifade olunur
    'django.contrib.messages', # olunan muracietin ughurla qeydealinib/alinmamasi ile baghli bir defelik mesajlar oturur,refresh-de itir
    'django.contrib.staticfiles', #django ile biz tekce API yox statikfayllarla dolu olan template istifade ede bilirik
    'core.apps.CoreConfig', # apps-i bura elave etmesek, core ichinde modelleri gormeyeceyik
    'blog_2', # tekce papkanin adini yazaraqda vere bilerik, ama tam yazmaq en uyghundur
    'about_1',
    # 'account.apps.AccountConfig',
    'account_1',
    'contact.apps.ContactConfig',
    'product.apps.ProductConfig',
    'modeltranslation', 
    'order.apps.OrderConfig',
    'rest_framework',
    # 'modeltranslation',
]
 
MIDDLEWARE = [ #jangonun bize verdiyi xususiyyetler / nedir? = request gonderirik sayta,servere, saytda response qaytarir. hemen o response olaraq qayidan shey middleware-inin ichidir
    'django.middleware.security.SecurityMiddleware',
    # 'app.middleware.force_default_middleware.force_default_language_middleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

] 

ROOT_URLCONF = 'app.urls' #elave urls yazilarsa core-a, o zaman istifade olur,nece? onu axtar
AUTH_USER_MODEL = 'account_1.Account'

# TEMPLATES = [ # anasehifede gostermek uchun
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [os.path.join(BASE_DIR, 'templates')], # os.join BASE_DIR-ye caladi 'templates'-i, BASEDIR-de templ. adinda papka olacaq
#         # artıq template-ləri gəlib əsas templates papkasının içində axtaracaq
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,"templates")], #templates/base icinde olanlari burda axtarir
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.context_processors.subject_renderer',
            ],
        },
    },
]


WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3', #default olaraq slqite ishledilir ama bashqa sql olamlidir
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': "my_project_db",
        'USER': "my_project_user",
        'PASSWORD': "d8y46KEACjMtdepRf5TaMjCod1gtBlh2A8XfFs0zrg",
        'HOST': "localhost", #burda localhost, .env ichinde servisin adı yazilir
        'PORT': "5432",
        # 'OPTIONS': {
        #     'options': '-c timezone=UTC',
        # }
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', #mes. ad soyad Eli Veliyev, shifrenide eliveliyev qoyanda deyirki tapmaq chox asandir
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', #eger shifre mes.8den azdisa uyarir
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', #common umumi shifreler demekdir, Azərbaycan olsa deyecekki daha guclu qoy
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGES = (
    ('en', 'English'),
    ('az', 'Azerbaijan'),
    ('tr', 'Turkish'),
)
LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)

MODELTRANSLATION_DEFAULT_LANGUAGE = "en"
MODELTRANSLATION_LANGUAGES = ("tr", "az", "en")



LANGUAGE_CODE = 'az'

TIME_ZONE = 'Asia/Baku'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
if PROD:
    STATIC_ROOT = os.path.join(BASE_DIR, 'static') # static root prod. == os.path.join(BASE_DIR, 'static')
else:
    STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')] # static root lokal. == 
    

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/' #login olunmayan səhifəyə daxil olarkən login səhifəyə yönləndirər bu kodla
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/login'
