# Generated by Django 5.0 on 2024-02-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_alter_category_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='child',
            field=models.ManyToManyField(blank=True, to='product.category'),
        ),
    ]
