# Generated by Django 3.2.23 on 2024-02-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_alter_category_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='child',
            field=models.ManyToManyField(blank=True, related_name='_product_category_child_+', to='product.Category'),
        ),
    ]
