# Generated by Django 5.0 on 2024-01-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subscribe_time', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'subscribed user',
                'verbose_name_plural': 'subscribed user',
            },
        ),
    ]
