# Generated by Django 5.0 on 2024-01-23 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_1', '0002_subscribeuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubscribeUser',
            new_name='SubscribedUser',
        ),
    ]
