# Generated by Django 4.2.7 on 2023-11-22 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactinfo_options_appealing_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appealing',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 22, 9, 17, 23, 958153, tzinfo=datetime.timezone.utc)),
        ),
    ]
