# Generated by Django 4.2.7 on 2023-11-22 09:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_appealing_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appealing',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
